
name: 'dbt_expectations_integration_tests'
version: '1.0'

profile: 'integration_tests'

# require-dbt-version: inherit this from dbt-utils

config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

require-dbt-version: ">=0.18.1"

vars:
    'dbt_date:time_zone': 'America/Los_Angeles'
    dbt_utils_dispatch_list: [spark_utils, dbt_expectations_integration_tests]

quoting:
    database: false
    identifier: false
    schema: false

models:
  schema: dbt_expectations_integration_tests
  materialized: table
